#!/usr/bin/env ypsilon
#!r6rs

(import (rnrs)
        (only (core) format)
        (only (lunula validation) guide)
        (errata validator)
        (xunit))

(define-syntax assert-validator
  (syntax-rules ()
    ((_ name)
     #t)
    ((_ name ((valid0 valid1 ...)) e ...)
     (begin
       (guide (name 'valid0 'valid1 ...)
         (lambda _ (add-failure (format "~a: ~s seems invalid" 'name '(valid0 valid1 ...))))
         values)
       (assert-validator name e ...)))
    ((_ name ((invalid0 invalid1 ...) message0 message1 ...) e ...)
     (begin
       (guide (name 'invalid0 'invalid1 ...)
         (lambda (ht)
           (define (symbol<? s0 s1) (string<? (symbol->string s0) (symbol->string s1)))
           (assert-equal? (vector-sort symbol<? '#(message0 message1 ...))
                          (vector-sort symbol<? (hashtable-keys ht))))
         (lambda _ (add-failure (format "~a: ~s seems valid" 'name '(invalid0 invalid1 ...)))))
       (assert-validator name e ...)))))

(assert-validator validate-year
                  (("2009"))
                  (("2000"))
                  (("1980"))
                  (("") invalid-year)
                  (("794") invalid-year)
                  (("3000") invalid-year)
                  (("12345") invalid-year)
                  )

(assert-validator validate-month
                  (("01"))
                  (("02"))
                  (("03"))
                  (("04"))
                  (("05"))
                  (("06"))
                  (("07"))
                  (("08"))
                  (("09"))
                  (("10"))
                  (("11"))
                  (("12"))
                  (("") invalid-month)
                  (("0") invalid-month)
                  (("00") invalid-month)
                  (("1") invalid-month)
                  (("2") invalid-month)
                  (("3") invalid-month)
                  (("4") invalid-month)
                  (("5") invalid-month)
                  (("6") invalid-month)
                  (("7") invalid-month)
                  (("8") invalid-month)
                  (("9") invalid-month)
                  (("13") invalid-month)
                  (("123") invalid-month)
                  )

(assert-validator validate-day
                  (("01"))
                  (("02"))
                  (("03"))
                  (("04"))
                  (("05"))
                  (("06"))
                  (("07"))
                  (("08"))
                  (("09"))
                  (("10"))
                  (("11"))
                  (("12"))
                  (("13"))
                  (("14"))
                  (("15"))
                  (("16"))
                  (("17"))
                  (("18"))
                  (("19"))
                  (("20"))
                  (("21"))
                  (("22"))
                  (("23"))
                  (("24"))
                  (("25"))
                  (("26"))
                  (("27"))
                  (("28"))
                  (("29"))
                  (("30"))
                  (("31"))
                  (("") invalid-day)
                  (("0") invalid-day)
                  (("1") invalid-day)
                  (("2") invalid-day)
                  (("3") invalid-day)
                  (("4") invalid-day)
                  (("5") invalid-day)
                  (("6") invalid-day)
                  (("7") invalid-day)
                  (("8") invalid-day)
                  (("9") invalid-day)
                  (("32") invalid-day)
                  (("300") invalid-day)
                  )

(assert-validator validate-isbn10/revision-name/year/month/day
                  ((("4894712741" "初版第15刷" "2006" "06" "15")))
                  ((("489471274" "初版第15刷" "2006" "06" "15")) invalid-isbn10)
                  ((("489471274" "" "2006" "06" "15")) invalid-isbn10 name-is-blank)
                  ((("489471274" "初版第15刷" "200" "06" "1")) invalid-isbn10 invalid-year invalid-day)
                  )

(assert-validator validate-/uuid
                  ((("1")))
                  ((("f9a7b492-b33f-438d-8a5a-0208d885e2a5")))
                  ((("")) uuid-is-blank)
                  ((("f9a7b492-b33f-438d-8a5a-0208d885e2a%")) uuid-invalid-char)
                  ((("f9a7b492-b33f-438d-8a5a-0208d885e2a5-")) uuid-too-long)
                  ((("f9a7b492-b33f-438d-8a5a-0208d885e2a%-")) uuid-invalid-char uuid-too-long)
                  )

(report)
