(doctype transitional)
(html
  (head
  (title "Errata")
  (link ((href "/stylesheet/errata.css") (rel "stylesheet") (type "text/css")))
  (script ((type "text/javascript") (src "/javascript/jquery-1.3.2.min.js")))
  (script ((type "text/javascript") (src "/javascript/jquery.corner.js")))
  (script ((type "text/javascript"))
          "$(document).ready(function() {$('div#links').corner();$('#menus').corner();});")
  )
 (body
  (div ((id "links")) (lambda (_ links) links))
  (div ((id "menus")) (lambda (_ links) "Hello, World."))
  (div ((id "bottom")) "generated by template 'static'")
  ))
